---
abstract: 'Provides deferred POE Session registration for SessionInstantiation objects'
author:
  - 'Nicholas Perez <nperez@cpan.org>'
build_requires:
  POE: 0
  POEx::Role::SessionInstantiation: 0
  POEx::Types: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-Trait-DeferredRegistration
requires:
  MooseX::Declare: 0
  POEx::Role::SessionInstantiation::Meta::Session::Magic: 0
resources:
  repository: git://github.com/nperez/pxtdr.git
version: 1.102770
