---
abstract: 'A Trait for SessionInstantiation to defer POE Session registration'
author:
  - 'Nicholas Perez <nperez@cpan.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092670'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-Trait-DeferredRegistration
requires:
  POEx::Role::SessionInstantiation: 0.092673
  Test::More: 0.92
resources:
  repository: git://github.com/nperez/pxtdr.git
version: 0.092681
